# Generated by Django 3.2.4 on 2021-06-11 12:57

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(verbose_name=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True))),
                ('name', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Coin name')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('total_value', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(20)], verbose_name='Total coin value')),
            ],
        ),
    ]
